apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-uuid
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-uuid
  template:
    metadata:
      labels:
        app: nginx-uuid
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            echo "<h1>Hello from pod with UUID: $POD_UUID</h1>" > /usr/share/nginx/html/index.html
            nginx -g "daemon off;"
        ports:
        - containerPort: 80